version: "3"
services:
  web:
    build: .
    command: bundle exec puma -v config.ru
    ports:
      - "80:9292"
    environment:
      REDIS_URL: redis://redis:6379
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: secstream
      MYSQL_PASSWORD: secstream
      MYSQL_DATABASE: secstream
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./stream.rb
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - db
volumes:
  db-data:
  redis-data:
