version: "3"
services:
  web:
    build: .
    command: bundle exec puma -v config.ru
    ports:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: secstream
      MYSQL_PASSWORD: secstream
      MYSQL_DATABASE: secstream
    volumes:
      - db-data:/var/lib/mysql
  stream:
    build: .
    command: ruby stream.rb
volumes:
  db-data:
